stages:
  - build
  - test
  - package
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export TAG=git log -1 --pretty=%h

build webstore:
  stage: build
  image: node:11-alpine
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - webstore
  script:
    - ./gradlew assemble
  only:
    - master
    - tags

test webstore:
  stage: test
  tags:
    - webstore
  script:
    - ./gradlew check
  only:
    - master
    - tags

package webstore:
  stage: package
  tags:
    - webstore
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN
    - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_REPOSITORY:$TAG .
    - docker push $CI_REGISTRY_USER/$CI_REGISTRY_REPOSITORY
  only:
    - master
    - tags

deploy webstore:
  stage: deploy
  tags:
    - webstore
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r build/libs/. ~/api-deployment
    - sudo service webstore restart
  only:
    - master
    - tags

