stages:
  - build
  - test
  - package
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export APP_CONTAINER_NAME=webstore-back-container
  - export DATABASE_CONTAINER_NAME=postgres-container
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN

build webstore:
  stage: build
  image: node:11-alpine
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - webstore
  script:
    - ./gradlew clean
    - ./gradlew assemble
  only:
    - master
    - tags

test webstore:
  stage: test
  tags:
    - webstore
  script:
    - ./gradlew check jacocoTestReport
    - cat ./build/jacocoHtml/index.html
  only:
    - master
    - tags

package webstore:
  stage: package
  tags:
    - webstore
  script:
    - bash ./scripts/package.sh
  only:
    - master
    - tags

deploy webstore:
  stage: deploy
  tags:
    - webstore
  script:
    - bash ./scripts/deploy.sh
  only:
    - master
    - tags

