version: '3.3'
services:
  db:
    image: postgres

    container_name: "webstore_postgres"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=webstoredb

    ports:
      - "5632:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data