version: '3.3'
services:
  db:
    image: postgres
    container_name: "webstore_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sakv41basvbwoiv45yhwrcbo
      - POSTGRES_DB=webstoredb
    ports:
      - "5632:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  testsdb:
    image: postgres
    ports:
      - "5633:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sakv41basvbwoiv45yhwrcbo
      - POSTGRES_DB=webstoredb
