info:
  app:
    name: Flower Store
    description: This is a webstore app for iti0203.

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: "dev"
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: thread
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://postgres-container:5432/webstoredb
    username: postgres
    password: 8Wxfeyrya1EbSpjyJOnITprw3rQDCJpe
    platform: postgres
  h2:
    console:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: INFO

---

spring:
  profiles: dev
logging:
  path: .
  file: logs/dev

---

spring:
  profiles: prod
logging:
  path: /logs/back
  file: prod
