server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/webstoredb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
