server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5632/postgres
    username: postgres
    password: sakv41basvbwoiv45yhwrcbo
    platform: postgres
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: thread
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
