info:
  app:
    name: Flower Store
    description: This is a webstore app for iti0203.

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: "dev"
  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:logback-spring.xml

app:
  jwt:
    secret: bRUG198EfyW3g7GF8yTufhKUjUbejrRKoJi3lqzZ2V3pYAzWowSTtBc7MOHix6R
    durationMin: 120

---

spring:
  profiles: dev
  jpa:
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/testdb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
logging:
  level:
    ROOT: DEBUG
  path: .
  file: logs/dev

---

spring:
  profiles: prod
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: thread
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://postgres-container:5432/webstoredb
    username: postgres
    password: testPassword
    platform: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    ROOT: ERROR
  path: /logs/back
  file: prod
